# Generated by Django 5.2.6 on 2025-09-22 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Users who have joined this event', related_name='events_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
