# Generated by Django 5.2.6 on 2025-09-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGIN_LOCKED', 'Login Locked'), ('LOGOUT', 'Logout'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('PASSWORD_CHANGED', 'Password Changed'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('EMERGENCY_ADMIN_ACCESS', 'Emergency Admin Access')], max_length=25),
        ),
    ]
