providers = ["python", "node"]

[start]
cmd = "bash entrypoint.sh"

# Optional: if you later need Node for Tailwind builds, Nixpacks
# will also provide Node because we listed it as a secondary provider.
