# Generated by Django 5.2.6 on 2025-09-22 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Cyblime-Cycling', max_length=100)),
                ('main_title', models.CharField(default='CYBLIME', max_length=50)),
                ('subtitle', models.CharField(default='BROOKLYN CYBLIME CYCLING CLUB', max_length=100)),
                ('hero_background', models.URLField(default='https://images.unsplash.com/photo-1571068316344-75bc76f77890?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80', help_text='Background image for hero section', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SlideshowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title/description', max_length=200)),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80', help_text='URL of the image (e.g., from unsplash, pexels, etc.)', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('caption', models.CharField(blank=True, help_text='Optional caption text', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show this image in slideshow')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slideshow Image',
                'verbose_name_plural': 'Slideshow Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
